---
title: "Integrate 10x Samples Low filtering"
author: "Joan Abinet"
date: "`r format (Sys.time(), format='%Y-%m-%d %H:%M:%S %z')`"
output:
  pdf_document:
    toc: true
    toc_depth: 2
  header-includes:
    -|
    ```{=latex}
    \usepackage{fvextra}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
      breaksymbolleft={}, 
      showspaces = false,
      showtabs = false,
      breaklines,
      commandchars=\\\{\}
    }
    ```
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 50), tidy = TRUE)
```

# Load Packages
```{r}
suppressMessages(library(dplyr))
suppressMessages(library(Seurat))
suppressMessages(library(patchwork))
suppressMessages(library(ggplot2))
suppressMessages(library(stringr))
suppressMessages(library(dittoSeq))
suppressMessages(library(ComplexHeatmap))
```


# Loading data
```{r, message=FALSE, warning=FALSE, results= "hide" }
all_dirs <- dir(path = "../10x-1-Pre_Processing/Data", full.names = T)

list_sample <- list()
for (i in 1:length(all_dirs)) {
  
  Seq_raw_file <- Read10X(data.dir = paste0(all_dirs[i]))
  Seurat_file <- CreateSeuratObject(counts = Seq_raw_file, project = str_sub(all_dirs[i],-8,-1), min.cells = 3, min.features =   100)
  
  Seurat_file[["percent.mt"]] <- PercentageFeatureSet(Seurat_file, pattern = "^MT-")
  Seurat_file <- subset(Seurat_file, subset = nFeature_RNA < 8000 & percent.mt < 20)# or 5 

  list_sample <- append(list_sample, Seurat_file)
}
```

```{r, message=FALSE, warning=FALSE, results= "hide" }
list_sample <- lapply(list_sample, function(x) {
  x <- NormalizeData(x, verbose = F)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000, verbose = F)
})
```

```{r, message=FALSE, warning=FALSE, results= "hide" }
features <- SelectIntegrationFeatures(list_sample, verbose = F)

list_sample <- lapply(list_sample, function (x) {
  x <- ScaleData(x, features = features, verbose = F)
  x <- RunPCA(x, features = features, verbose = F)
})
```

```{r, message=FALSE, warning=FALSE, results= "hide" }
BAL.anchors <- FindIntegrationAnchors(object.list = list_sample, anchor.features = features, reduction = "rpca")

BAL_10x.integrated <- IntegrateData(anchorset = BAL.anchors)
```

```{r, message=FALSE, warning=FALSE, results= "hide" }
DefaultAssay(BAL_10x.integrated) <- "integrated"

# Run the standard workflow for visualization and clustering
BAL_10x.integrated <- ScaleData(BAL_10x.integrated, verbose = FALSE)
BAL_10x.integrated <- RunPCA(BAL_10x.integrated, npcs = 30, verbose = FALSE)
BAL_10x.integrated <- RunUMAP(BAL_10x.integrated, reduction = "pca", dims = 1:15)
BAL_10x.integrated <- FindNeighbors(BAL_10x.integrated, reduction = "pca", dims = 1:15)
BAL_10x.integrated <- FindClusters(BAL_10x.integrated, resolution = 0.35)
```

```{r}
color_pallette <- c("#FF5733", "#33A02C", "#3357FF", "#FF33A1", "yellow", "#33FFF5", "#A133FF", "#FF8C00", "#57FF33", "#5733FF", "#78550b")

DimPlot(BAL_10x.integrated, cols = color_pallette)
#ggsave("umap10x_lowQC.pdf", width = 8, height = 4)
```

```{r}
FeaturePlot(BAL_10x.integrated, features = "nFeature_RNA")
#ggsave("10x_lowQc_ngene.pdf", width = 8, height = 4)
```

```{r, message=FALSE, warning=FALSE}
DefaultAssay(BAL_10x.integrated) <- "RNA"
Marker_gene <- c("FABP4", "MARCO", "CD68", "C1QC", "MRC1", "MKI67", "TOP2A", "CSF1R", "VCAN", "CD14",
"MAFB", "CSF3R", "FCGR3B", "CXCR2", "S100A8", "S100A9", "CD3E", "CD8A", "GZMB",
"KLGR1", "KLRK1", "CD4", "IL7R", "KIT", "CPA3", "EPCAM", "KRT8", "CDH1", "SIGLEC8", "CCR3",
"SYNE1")

DotPlot(BAL_10x.integrated, features = Marker_gene) + theme_classic() + theme(axis.text.x = element_text(angle = 45, hjust = 1))
#ggsave("Dotplot_10X_LowQC_nonAnnotated.pdf", width = 35, height = 10)
```

```{r}
BAL_10x.integrated$Annotation <- BAL_10x.integrated$seurat_clusters 
BAL_10x.integrated$Annotation <- as.factor(BAL_10x.integrated$Annotation)

levels(BAL_10x.integrated$Annotation) <- c("C1 - AM", "C5 - CD8+ T cell", "C10 - Unidentified", "C6 - CD4+ T cell", "C2 - AM", "C4 - Neu", "C11 - Unidentified", "C3 - Mafb+ MoMac", "C9 - Epithelial cell", "C7 - Cycling cell", "C8 - Mast cell")

BAL_10x.integrated$Annotation <- factor(BAL_10x.integrated$Annotation, levels =  c("C1 - AM", "C2 - AM", "C3 - Mafb+ MoMac", "C4 - Neu", "C5 - CD8+ T cell", "C6 - CD4+ T cell", "C7 - Cycling cell", "C8 - Mast cell", "C9 - Epithelial cell", "C10 - Unidentified", "C11 - Unidentified"))

color_pallette <- c("#FF5733", "#33A02C", "#3357FF", "#FF33A1", "yellow", "#33FFF5", "#A133FF", "#FF8C00", "#57FF33", "#5733FF", "#78550b")

DimPlot(BAL_10x.integrated, group.by = "Annotation", cols = color_pallette)
#ggsave("Umap_LowQC_Annotation.pdf", width = 8, height = 4) 
```

```{r, message=FALSE, warning=FALSE}
DefaultAssay(BAL_10x.integrated) <- "RNA"
Marker_gene <- c("FABP4", "MARCO", "CD68", "C1QC", "MRC1", "MKI67", "TOP2A", "CSF1R", "VCAN", "CD14",
"MAFB", "CSF3R", "FCGR3B", "CXCR2", "S100A8", "S100A9", "CD3E", "CD8A", "GZMB",
"KLGR1", "KLRK1", "CD4", "IL7R", "KIT", "CPA3", "EPCAM", "KRT8", "CDH1", "SIGLEC8", "CCR3",
"SYNE1")

DotPlot(BAL_10x.integrated, features = Marker_gene, group.by = "Annotation")+ theme_classic() + theme(axis.text.x = element_text(angle = 45, hjust = 1))
#ggsave("Dotplot_10X_LowQC_Annotated.pdf", width = 35, height = 10)

```

```{r, message=FALSE, warning=FALSE, results= "hide"}
Idents(BAL_10x.integrated) <- "Annotation"

lavage.markers <- FindAllMarkers(BAL_10x.integrated, only.pos = TRUE, min.pct = 0.25)

lavage.markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = avg_log2FC) -> top10

mat <- as.matrix( GetAssayData(object = BAL_10x.integrated, slot = "data")[as.character(top10$gene),])

df <- as.data.frame(BAL_10x.integrated$Annotation)
colnames(df) <- "Clusters"
color_df <- list(Clusters = c("C1 - AM" = "#FF5733", 
                              "C2 - AM" = "#33A02C", 
                              "C3 - Mafb+ MoMac" = "#3357FF", 
                              "C4 - Neu" = "#FF33A1", 
                              "C5 - CD8+ T cell" = "yellow", 
                              "C6 - CD4+ T cell" = "#33FFF5", 
                              "C7 - Cycling cell" = "#A133FF", 
                              "C8 - Mast cell" = "#FF8C00", 
                              "C9 - Epithelial cell" = "#57FF33", 
                              "C10 - Unidentified" = "#5733FF", 
                              "C11 - Unidentified" = "#78550b"))

Heatmap<- Heatmap(t(scale(t(mat))), show_column_names = F,
        column_split = BAL_10x.integrated$Annotation,
        cluster_column_slices = F,
        cluster_rows = F,
        top_annotation = HeatmapAnnotation(df = df, col = color_df),
        use_raster = F,
        show_heatmap_legend = F,
        show_column_dend = F,
        column_title_rot = 90,
        row_names_side = "left")

#tidyHeatmap::save_pdf(Heatmap, "Heatmap_10x_low.pdf", width = 35, height = 50, units ="cm")        
```

# Heatmap top genes per clusters
```{r fig.width=10, fig.height=20}
Heatmap
```

```{r}
sessionInfo()
```

