---
title: "Integrate Hive Samples Low filtering"
author: "Joan Abinet"
date: "`r format (Sys.time(), format='%Y-%m-%d %H:%M:%S %z')`"
output:
  pdf_document:
    toc: true
    toc_depth: 2
  header-includes:
    -|
    ```{=latex}
    \usepackage{fvextra}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
      breaksymbolleft={}, 
      showspaces = false,
      showtabs = false,
      breaklines,
      commandchars=\\\{\}
    }
    ```
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 50), tidy = TRUE)
```

# Load Packages
```{r}
suppressMessages(library(dplyr))
suppressMessages(library(Seurat))
suppressMessages(library(patchwork))
suppressMessages(library(ggplot2))
suppressMessages(library(stringr))
suppressMessages(library(dittoSeq))
suppressMessages(library(ComplexHeatmap))
```

# Loading data
```{r, message=FALSE, warning=FALSE, results= "hide"}
all_dirs <- dir(path = "../Hive-1-Pre_Processing/Data", full.names = T)

list_sample <- list()
for (dir in all_dirs) {
  
  files <- list.files(dir)
  Count_file <- files[grep("TCM.tsv.gz$", files)]
  Countdata <- read.table(paste0(dir,"/",Count_file), sep = "\t", header = T, row.names=1) 
  
  Lavage_cellsHive <- CreateSeuratObject(counts = Countdata, project = str_sub(dir,-5,-1), min.features = 100)
  
  Lavage_cellsHive[["percent.mt"]] <- PercentageFeatureSet(Lavage_cellsHive, pattern = "^MT-")# MT : human cells
  Lavage_cellsHive <- subset(Lavage_cellsHive, subset = nFeature_RNA < 8000 & percent.mt < 20)# or 5 
  list_sample <- append(list_sample, Lavage_cellsHive)
}
```


```{r, message=FALSE, warning=FALSE, results= "hide"}
list_sample <- lapply(list_sample, function(x) {
  x <- NormalizeData(x, verbose = F)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000, verbose = F)
})
```


```{r, message=FALSE, warning=FALSE, results= "hide"}
features <- SelectIntegrationFeatures(list_sample)

list_sample <- lapply(list_sample, function (x) {
  x <- ScaleData(x, features = features, verbose = F)
  x <- RunPCA(x, features = features, verbose = F)
})
```


```{r, message=FALSE, warning=FALSE, results= "hide"}
BAL.anchors <- FindIntegrationAnchors(object.list = list_sample, anchor.features = features, reduction = "rpca", verbose = F)

BAL_Hive.integrated <- IntegrateData(anchorset = BAL.anchors, verbose = F)
```

```{r, message=FALSE, warning=FALSE, results= "hide"}
DefaultAssay(BAL_Hive.integrated) <- "integrated"

# Run the standard workflow for visualization and clustering
BAL_Hive.integrated <- ScaleData(BAL_Hive.integrated, verbose = FALSE)
BAL_Hive.integrated <- RunPCA(BAL_Hive.integrated, npcs = 30, verbose = FALSE)
BAL_Hive.integrated <- RunUMAP(BAL_Hive.integrated, reduction = "pca", dims = 1:15)
BAL_Hive.integrated <- FindNeighbors(BAL_Hive.integrated, reduction = "pca", dims = 1:15)
BAL_Hive.integrated <- FindClusters(BAL_Hive.integrated, resolution = 0.5)
```

```{r}
DimPlot(BAL_Hive.integrated, reduction = "umap", group.by = "orig.ident")
```

```{r}
DimPlot(BAL_Hive.integrated, reduction = "umap", label = T)
```

# Gene number
```{r}
FeaturePlot(BAL_Hive.integrated, features = "nFeature_RNA", cols = c("lightgray", "darkorange"))
#ggsave("FeaturePlot_geneCount_low.pdf", width = 8, height = 4) 
```

# Annotation
```{r, message=FALSE, warning=FALSE}
DefaultAssay(BAL_Hive.integrated) <- "RNA"
Marker_gene <- c("FABP4", "MARCO", "CD68", "C1QC", "MRC1", "MKI67", "TOP2A", "CSF1R", "VCAN", "CD14",
"MAFB", "CSF3R", "FCGR3B", "CXCR2", "S100A8", "S100A9", "CD3E", "CD8A", "GZMB",
"KLGR1", "KLRK1", "CD4", "IL7R", "KIT", "CPA3", "EPCAM", "KRT8", "CDH1", "SIGLEC8", "CCR3",
"SYNE1")

DotPlot(BAL_Hive.integrated, features = Marker_gene, cols = c("lightgray", "darkorange"))+ theme_classic() + theme(axis.text.x = element_text(angle = 45, hjust = 1))
#ggsave("Dotplot_10X_LowQC_Annotated.pdf", width = 35, height = 10)
```

# Annotating cluster
```{r}
BAL_Hive.integrated$Annotation <- BAL_Hive.integrated$seurat_clusters 
BAL_Hive.integrated$Annotation <- as.factor(BAL_Hive.integrated$Annotation)
levels(BAL_Hive.integrated$Annotation) <- c("C8 - T cell", "C1 - AM", "C16 - Unidentified",  "C2 - AM", "C3 - AM", "C7 - Neu", "C4 - AM", "C5 - AM", "C9 - T cell", "C10 - T cell", "C6 - Mafb+ MoMac", "C12 - Epithelial cell", "C11 - Eos", "C13 - Mast cell", "C14 - Cycling cell", "C15 - Unidentified")

BAL_Hive.integrated$Annotation <- factor(BAL_Hive.integrated$Annotation, levels =  c("C1 - AM", "C2 - AM", "C3 - AM", "C4 - AM", "C5 - AM", "C6 - Mafb+ MoMac", "C7 - Neu", "C8 - T cell", "C9 - T cell", "C10 - T cell", "C11 - Eos", "C12 - Epithelial cell", "C13 - Mast cell", "C14 - Cycling cell", "C15 - Unidentified", "C16 - Unidentified"))

my_palette <- c("#ff9305", "lightblue","#877f5f","#F0E442", "#0072B2","#28FC37","#CC79A7", "#c0bec2", "#854e07", "#a865eb", "#00A087","#FF9DA7", "#A55AFF", "#8C4B4B","#FC2848", "turquoise")

DimPlot(BAL_Hive.integrated, group.by = "Annotation", cols = my_palette)
#ggsave("Umap_Annotation_low.pdf", width = 8, height = 4) 

```

# Dotplot Annotated
```{r, message=FALSE, warning=FALSE}
DefaultAssay(BAL_Hive.integrated) <- "RNA"
Marker_gene <- c("FABP4", "MARCO", "CD68", "C1QC", "MRC1", "MKI67", "TOP2A", "CSF1R", "VCAN", "CD14",
"MAFB", "CSF3R", "FCGR3B", "CXCR2", "S100A8", "S100A9", "CD3E", "CD8A", "GZMB",
"KLGR1", "KLRK1", "CD4", "IL7R", "KIT", "CPA3", "EPCAM", "KRT8", "CDH1", "SIGLEC8", "CCR3",
"SYNE1")

DotPlot(BAL_Hive.integrated, features = Marker_gene, group.by = "Annotation", cols = c("lightgray", "darkorange"))+ theme_classic() + theme(axis.text.x = element_text(angle = 45, hjust = 1))
#ggsave("Dotplot_10X_LowQC_Annotated.pdf", width = 35, height = 10)
```

```{r, message=FALSE, warning=FALSE, results= "hide"}
Idents(BAL_Hive.integrated) <- "Annotation"
lavage.markers <- FindAllMarkers(BAL_Hive.integrated, only.pos = TRUE, min.pct = 0.25)

lavage.markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = avg_log2FC) -> top10

mat <- as.matrix(GetAssayData(object = BAL_Hive.integrated, slot = "data")[as.character(top10$gene),])

df <- as.data.frame(BAL_Hive.integrated$Annotation)
colnames(df) <- "Clusters"
color_df <- list(Clusters = c("C1 - AM" = "#ff9305", 
                              "C2 - AM" = "lightblue", 
                              "C3 - AM" = "#877f5f", 
                              "C4 - AM" = "#F0E442",
                              "C5 - AM" = "#0072B2",
                              "C6 - Mafb+ MoMac" = "#28FC37", 
                              "C7 - Neu" = "#CC79A7",
                              "C8 - T cell" = "#c0bec2", 
                              "C9 - T cell" = "#854e07", 
                              "C10 - T cell" = "#a865eb", 
                              "C11 - Eos" = "#00A087",
                              "C12 - Epithelial cell" = "#FF9DA7",
                              "C13 - Mast cell" = "#A55AFF",
                              "C14 - Cycling cell" = "#8C4B4B",
                              "C15 - Unidentified" = "#FC2848",
                              "C16 - Unidentified" = "turquoise"))

Heatmap <- Heatmap(t(scale(t(mat))), show_column_names = F,
        column_split = BAL_Hive.integrated$Annotation,
        cluster_column_slices = F,
        cluster_rows = F,
        top_annotation = HeatmapAnnotation(df = df, col = color_df),
        use_raster = F,
        show_heatmap_legend = F,
        show_column_dend = F,
        column_title_rot = 90,
        row_names_side = "left")

#tidyHeatmap::save_pdf(Heatmap, "Heatmap_Hive_low.pdf",width = 30, height = 45, units ="cm")

```

# Heatmap top genes per clusters
```{r fig.width=10, fig.height=20}
Heatmap
```

```{r}
sessionInfo()
```
