---
title: "Annotation cells"
author: "Joan Abinet"
date: "`r format (Sys.time(), format='%Y-%m-%d %H:%M:%S %z')`"
output:
  pdf_document:
    toc: true
    toc_depth: 2
  header-includes:
    -|
    ```{=latex}
    \usepackage{fvextra}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
      breaksymbolleft={}, 
      showspaces = false,
      showtabs = false,
      breaklines,
      commandchars=\\\{\}
    }
    ```
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 50), tidy = TRUE)
```

# Load Packages
```{r}
suppressMessages(library(dplyr))
suppressMessages(library(Seurat))
suppressMessages(library(patchwork))
suppressMessages(library(ggplot2))
suppressMessages(library(stringr))
suppressMessages(library(dittoSeq))
suppressMessages(library(ComplexHeatmap))
```

# Load Seurat objects
```{r}
BAL_10x.integrated <- readRDS("../10x-1-Pre_Processing/BAL_10x.integrated_noDB.rds")

DimPlot(BAL_10x.integrated, label = T)
```

# Annotating clusters
```{r, message=FALSE, warning=FALSE}
markers_neutro <- c("CSF3R", "FCGR3B", "CXCR2", "S100A8", "S100A9")
marker_epi <- c("EPCAM", "KRT8", "CDH1","SIGLEC8")
Marker_Cycling_cell <- c("MKI67", "TOP2A")
markers_AM <- c("FABP4", "MARCO", "CD68", "C1QC", "MRC1")
markers_Mafb_macro <- c("CSF1R", "VCAN", "CD14","MAFB")
markers_Mast <- c("KIT", "CPA3")
markers_LT <- c("CD3E", "CD8A", "GZMB","KLGR1", "KLRK1", "CD4", "IL7R")

DotPlot(BAL_10x.integrated, features = c(markers_AM, markers_Mafb_macro, markers_neutro, markers_LT, markers_Mast, Marker_Cycling_cell, marker_epi)) + theme_classic()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

# Annotation
```{r}
BAL_10x.integrated$Annotation <- BAL_10x.integrated$seurat_clusters 
BAL_10x.integrated$Annotation <- as.factor(BAL_10x.integrated$Annotation)
levels(BAL_10x.integrated$Annotation) <- c("C6 - CD8+ T cell", "C1 - AM", "C2 - AM", "C7 - CD4+ T cell", "C5 - Neu", "C4 - Mafb+ MoMac", "C9 - Cycling cell", "C3 - AM", "C11 - Epithelial cell", "C8 - Others T cell", "C10 - Mast cell")

BAL_10x.integrated$Annotation <- factor(BAL_10x.integrated$Annotation, levels =  c("C1 - AM", "C2 - AM", "C3 - AM", "C4 - Mafb+ MoMac", "C5 - Neu", "C6 - CD8+ T cell", "C7 - CD4+ T cell", "C8 - Others T cell", "C9 - Cycling cell", "C10 - Mast cell", "C11 - Epithelial cell"))

col <- c("#E2B80C", "#998025", "#AE8052", "#0F8140", "#4F2569", "#ABD6E4", "#1CB7D5", "#6B7BBA", "#2D368B", "#DF15AE", "#BDBCBC")

DimPlot(BAL_10x.integrated, group.by = "Annotation", cols = col)
#ggsave("Umap_Annotation.pdf", width = 8, height = 4) 
DimPlot(BAL_10x.integrated, reduction = "umap", group.by = "orig.ident")+ theme(legend.text	 = element_text(size = 15)) + labs(title = NULL)
#ggsave("Umap_PerSample.pdf", width = 8, height = 4) 
```

# Dotplot Annotated
```{r fig.width=20, fig.height=8, message=FALSE, warning=FALSE}
DefaultAssay(BAL_10x.integrated) <- "RNA"

Marker_gene <- c("FABP4", "MARCO", "CD68", "C1QC", "MRC1", "MKI67", "TOP2A", "CSF1R", "VCAN", "CD14",
"MAFB", "CSF3R", "FCGR3B", "CXCR2", "S100A8", "S100A9", "CD3E", "CD8A", "GZMB",
"KLGR1", "KLRK1", "CD4", "IL7R", "KIT", "CPA3", "EPCAM", "KRT8", "CDH1", "SIGLEC8", "CCR3",
"SYNE1")

DotPlot(BAL_10x.integrated, features = Marker_gene, group.by = "Annotation") + theme_classic() + scale_size(range = c(0,12)) + theme(axis.text.x = element_text(angle = 45, hjust = 1), axis.text = element_text(size = 35),
           legend.text	 = element_text(size = 25), legend.key.height= unit(1, 'cm'),
        legend.key.width= unit(2, 'cm'))

#ggsave("Dotplot_Annotated.pdf", width = 35, height = 10)
```


```{r, message=FALSE, warning=FALSE, results= "hide" }
Idents(BAL_10x.integrated) <- "Annotation"

lavage.markers <- FindAllMarkers(BAL_10x.integrated, only.pos = TRUE, min.pct = 0.25)

lavage.markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = avg_log2FC) -> top10

mat <- as.matrix( GetAssayData(object = BAL_10x.integrated, slot = "data")[as.character(top10$gene),])

df <- as.data.frame(BAL_10x.integrated$Annotation)
colnames(df) <- "Clusters"
color_df <- list(Clusters = c("C1 - AM" = "#E2B80C", 
                              "C2 - AM" = "#998025", 
                              "C3 - AM" = "#AE8052", 
                              "C4 - Mafb+ MoMac" = "#0F8140", 
                              "C5 - Neu" = "#4F2569", 
                              "C6 - CD8+ T cell" = "#ABD6E4", 
                              "C7 - CD4+ T cell" = "#1CB7D5", 
                              "C8 - Others T cell" = "#6B7BBA", 
                              "C9 - Cycling cell" = "#2D368B", 
                              "C10 - Mast cell" = "#DF15AE", 
                              "C11 - Epithelial cell" = "#BDBCBC"))

Heatmap<- Heatmap(t(scale(t(mat))), show_column_names = F,
        column_split = BAL_10x.integrated$Annotation,
        cluster_column_slices = F,
        cluster_rows = F,
        top_annotation = HeatmapAnnotation(df = df, col = color_df),
        use_raster = F,
        show_heatmap_legend = F,
        show_column_dend = F,
        column_title_rot = 90,
        row_names_side = "left")

#tidyHeatmap::save_pdf(Heatmap, "Heatmap_10x.pdf", width = 35, height = 50, units ="cm")        
```

# Heatmap top genes per clusters
```{r fig.width=10, fig.height=20}
Heatmap
```

# Cluster frequency per sample
```{r}
var_order <- c(1,4,5,6,7,8,9,10,11,2,3)
dittoBarPlot(BAL_10x.integrated, "Annotation", group.by ="orig.ident", var.labels.reorder = var_order, color.panel = col)

#ggsave("bar_freq_10x.pdf")
```

# Saving results for later
```{r, eval=FALSE}
saveRDS(BAL_10x.integrated,"BAL_10x.annotated_noDB.rds")
```

```{r}
sessionInfo()
```


