---
title: "10x data Annotation"
author: "Abinet Joan"
date: "`r format (Sys.time(), format='%Y-%m-%d %H:%M:%S %z')`"
output:
  pdf_document: 
    toc: true
    toc_depth: 2
  html_document: default
header-includes:
  - |
    ```{=latex}
    \usepackage{fvextra}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
      breaksymbolleft={}, 
      showspaces = false,
      showtabs = false,
      breaklines,
      commandchars=\\\{\}
    }
    ```
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading packages
```{r}
suppressMessages(library(dplyr))
suppressMessages(library(Seurat))
suppressMessages(library(patchwork))
suppressMessages(library(ggplot2))
suppressMessages(library(RColorBrewer))
suppressMessages(library(dittoSeq))
suppressMessages(library(ComplexHeatmap))
suppressMessages(library(formatR))
```

# Loading data
```{r}
Cell_10xAnnotate <- readRDS("../10X-1-Processing/lavage_cells10x.rds")
```


```{r fig.width=6, fig.height=4}
DimPlot(Cell_10xAnnotate, reduction = "umap", group.by = "orig.ident")+ theme(legend.text	 = element_text(size = 15)) + labs(title = NULL)
#ggsave("Umap_PerSample.pdf", width = 8, height = 4) 
```

# Annotation
```{r fig.width=6, fig.height=4}
Cell_10xAnnotate$Annotation <- Cell_10xAnnotate$seurat_clusters
levels(Cell_10xAnnotate$Annotation) <- c("C1 - AM", "C10 - CD8+ T cell", "C8 - CD4+ T cell", "C4 - Mafb+ MoMac", "C11 - CD4+ T cell", "C5 - Neu", "C2 - AM", "C7 - CD8+ T cell", "C9 - CD8+ T cell", "C13 - Epithelial cell", "C6 - Neu", "C12 - Mast cell", "C3 - Cycling AM")

Cell_10xAnnotate$Annotation <- factor(Cell_10xAnnotate$Annotation, levels =  c("C1 - AM", "C2 - AM", "C3 - Cycling AM", "C4 - Mafb+ MoMac", "C5 - Neu", "C6 - Neu", "C7 - CD8+ T cell", "C8 - CD4+ T cell", "C9 - CD8+ T cell", "C10 - CD8+ T cell", "C11 - CD4+ T cell", "C12 - Mast cell",  "C13 - Epithelial cell"))


# Je modifie les couleurs pour qu'elles soient égalent à celle du HIVE
col <- c("#E2B80C", "#998025", "#AE8052", "#0F8140",  "#8A6892", "#4F2569", "#ABD6E4", "#79C7CB", "#6B7BBA", "#2D368B", "#1CB7D5", "#DF15AE", "#BDBCBC")

DimPlot(Cell_10xAnnotate, group.by = "Annotation", cols = col)+ theme(legend.text	 = element_text(size = 15)) + labs(title = NULL)
#ggsave("Umap_Annotation.pdf", width = 8, height = 4) 
```

```{r, message=FALSE, warning=FALSE, results= "hide"}
Idents(Cell_10xAnnotate) <- "Annotation"

lavage.markers <- FindAllMarkers(Cell_10xAnnotate, only.pos = TRUE, min.pct = 0.25)

lavage.markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = avg_log2FC) -> top10

mat <- as.matrix( GetAssayData(object = Cell_10xAnnotate, slot = "data")[as.character(top10$gene),])

df <- as.data.frame(Cell_10xAnnotate$Annotation)
colnames(df) <- "Clusters"
color_df <- list(Clusters = c("C1 - AM" = "#E2B80C", 
                              "C2 - AM" = "#998025", 
                              "C3 - Cycling AM" = "#AE8052", 
                              "C4 - Mafb+ MoMac" = "#0F8140", 
                              "C5 - Neu" = "#8A6892", 
                              "C6 - Neu" = "#4F2569", 
                              "C7 - CD8+ T cell" = "#ABD6E4", 
                              "C8 - CD4+ T cell" = "#79C7CB", 
                              "C9 - CD8+ T cell" = "#6B7BBA", 
                              "C10 - CD8+ T cell" = "#2D368B", 
                              "C11 - CD4+ T cell" = "#1CB7D5",
                              "C12 - Mast cell" = "#DF15AE",
                              "C13 - Epithelial cell" = "#BDBCBC"))


Heatmap<- Heatmap(t(scale(t(mat))), show_column_names = F,
        column_split = Cell_10xAnnotate$Annotation,
        cluster_column_slices = F,
        cluster_rows = F,
        top_annotation = HeatmapAnnotation(df = df, col = color_df),
        use_raster = F,
        show_heatmap_legend = F,
        show_column_dend = F,
        column_title_rot = 90,
        row_names_side = "left")

# tidyHeatmap::save_pdf(Heatmap, "Heatmap_10x.pdf", width = 35, height = 50, units ="cm")        
```

# Heatmap top genes per clusters
```{r fig.width=10, fig.height=20}
Heatmap
```


```{r fig.width=20, fig.height=8}
markers_neutro <- c("CSF3R","FCGR3B", "NAMPT", "CXCR2", "S100A8", "S100A9")
marker_epi <- c("EPCAM", "KRT8", "CDH1", "MUC1")
Marker_NK <- c("TRDC", "GNLY", "KLRD1", "KLRK1")
markers_AM <- c("C1QA", "C1QB", "C1QC", "FABP4")
markers_mono <- c("CSF1R", "TMEM176B", "NR4A2")
markers_baso <- c("HDC", "MS4A2", "GATA2", "CPA3", "TPSAB1")
markers_CD8 <- c("CD8A", "CLIC3")
Markers_CD4 <- c("CD4", "IL7R")


DotPlot(Cell_10xAnnotate, features = c(markers_AM, markers_mono, "VCAN","MAFB", markers_neutro, "MKI67", "TOP2A", markers_CD8, Markers_CD4, markers_baso, marker_epi), group.by = "Annotation") + theme_classic() + scale_size(range = c(0,12)) + theme(axis.text.x = element_text(angle = 45, hjust = 1), axis.text = element_text(size = 35),
           legend.text	 = element_text(size = 25), legend.key.height= unit(1, 'cm'),
        legend.key.width= unit(2, 'cm'))

#ggsave("Dotplot_annotated.pdf", width = 35, height = 10)
```

```{r fig.width=5, fig.height=10}
var_order <- c(1,6,7,8,9,10,11,12,13,2,3,4,5)
dittoBarPlot(Cell_10xAnnotate, "Annotation", group.by ="orig.ident", var.labels.reorder = var_order, color.panel = col)

#ggsave("bar_freq_10x.pdf")
```

```{r}
#saveRDS(Cell_10xAnnotate, "lavage_10x_annotated.rds")
```


```{r}
sessionInfo()
```

