---
title: "Data low QC"
author: "Abinet Joan"
date: "`r format (Sys.time(), format='%Y-%m-%d %H:%M:%S %z')`"
output:
  pdf_document: 
    toc: true
    toc_depth: 2
  html_document: default
header-includes:
  - |
    ```{=latex}
    \usepackage{fvextra}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
      breaksymbolleft={}, 
      showspaces = false,
      showtabs = false,
      breaklines,
      commandchars=\\\{\}
    }
    ```
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading packages
```{r}
suppressMessages(library(dplyr))
suppressMessages(library(Seurat))
suppressMessages(library(patchwork))
suppressMessages(library(ggplot2))
suppressMessages(library(writexl))
suppressMessages(library(SingleR))
suppressMessages(library(scuttle))
suppressMessages(library(scRNAseq))
suppressMessages(library(RColorBrewer))
suppressMessages(library(stringr))
suppressMessages(library(formatR))
```

# Loading data
```{r, message=FALSE, warning=FALSE, results= "hide"}
setwd("../10X-1-Processing")
# The path should be modifie to include your directory of the cellranger output
all_dirs <- dir(path = "Data/outs/per_sample_outs/", full.names = T)

list_sample <- list()
for (i in 1:length(all_dirs)) {
  
  # here the file path describe the filtered matrix from cellranger output
  Seq_raw_file <- Read10X(data.dir = paste0(all_dirs[i],"/count/sample_raw_feature_bc_matrix/"))
  Seurat_file <- CreateSeuratObject(counts = Seq_raw_file, project = str_sub(all_dirs[i],-8,-1), min.cells = 3, min.features =   100)
  list_sample <- append(list_sample, Seurat_file)
}

lavage_cells10x <- merge(list_sample[[1]], y = list_sample[-1], add.cell.ids = c("1","2","3", "4"), project = "bronchoalveolar_cells")
```

# QC
```{r fig.width=6, fig.height=4}
lavage_cells10x[["percent.mt"]] <- PercentageFeatureSet(lavage_cells10x, pattern = "^MT-")# MT : human cells
lavage_cells10x <- subset(lavage_cells10x, subset = nFeature_RNA < 8000 & percent.mt < 20)# or 5 
VlnPlot(lavage_cells10x, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), group.by = "orig.ident", ncol = 3, pt.size = 0.1)
#ggsave("VlnPlot_QC.png", height = 8, width = 12)
```

# Normalisation + scalin
```{r, message=FALSE, warning=FALSE, results= "hide"}
lavage_cells10x <- NormalizeData(lavage_cells10x, normalization.method = "LogNormalize", scale.factor = 10000)
lavage_cells10x <- FindVariableFeatures(lavage_cells10x, selection.method = "vst", nfeatures = 2000) 

all.genes <- rownames(lavage_cells10x)
lavage_cells10x <- ScaleData(lavage_cells10x, features = all.genes)
```

# Dimension reduction
```{r, message=FALSE, warning=FALSE, results= "hide"}
lavage_cells10x <- RunPCA(lavage_cells10x, features = VariableFeatures(object = lavage_cells10x))
#DimPlot(lavage_cells10x, reduction = "pca")

lavage_cells10x <- FindNeighbors(lavage_cells10x, dims = 1:16)
lavage_cells10x <- FindClusters(lavage_cells10x, resolution = 0.5) 
lavage_cells10x <- RunUMAP(lavage_cells10x, dims = 1:16)
```

# Umap
```{r fig.width=8, fig.height=4}
lavage_cells10x$Annotation <- lavage_cells10x$seurat_clusters
lavage_cells10x$Annotation <- as.factor(lavage_cells10x$Annotation)
levels(lavage_cells10x$Annotation) <- c("C1-AM", "C2-Unidentified", "C3-AM", "C4-T cell", "C5-Unidentified", "C6-T cell", "C7-T cell", "C8-Neutro", "C9-Mo-Mac", "C10-T cell", "C11-Unidentified", "C12-Epithelial Cell", "C13-AM", "C14-Mast Cell")

color_pallette <- c("#FF5733", "#33A02C", "#3357FF", "#FF33A1", "yellow", "#33FFF5", "#A133FF", "#FF8C00", "#57FF33", "#5733FF", "#78550b", "#33A1FF", "#FF33FF", "#0fc0db")

DimPlot(lavage_cells10x, reduction = "umap", group.by = "Annotation", cols = color_pallette)
```

```{r fig.width=20, fig.height=8}
Marker_gene <- c("FABP4", "MARCO", "CD68", "C1QC", "MRC1", "MKI67", "TOP2A", "CSF1R", "VCAN", "CD14",
"MAFB", "CSF3R", "FCGR3B", "CXCR2", "S100A8", "S100A9", "CD3E", "CD8A", "GZMB",
"KLGR1", "KLRK1", "CD4", "IL7R", "KIT", "CPA3", "EPCAM", "KRT8", "CDH1", "SIGLEC8", "CCR3",
"SYNE1")

DotPlot(lavage_cells10x, features = Marker_gene, group.by = "Annotation") + theme_classic() + scale_size(range = c(0,12)) + theme(axis.text.x = element_text(angle = 45, hjust = 1), axis.text = element_text(size = 35),
           legend.text	 = element_text(size = 25), legend.key.height= unit(1, 'cm'),
        legend.key.width= unit(2, 'cm'))

#ggsave("plot_lastMinute/Dotplot_10X.pdf", width = 35, height = 10)
```


```{r fig.width=6, fig.height=4}
FeaturePlot(lavage_cells10x, features = c("nFeature_RNA"))+ scale_color_gradient(low = "grey", high = "blue", limit = c(0,7960) )
#ggsave("nFeature.pdf", width = 8, height = 4)
```


```{r}
sessionInfo()
```

